project:
  type: book

book:
  title: "Statistical Computing - Practical One"
  date: "5 February 2025"
  chapters:
    - index.qmd
    - questionone.qmd
    - questionTwo.qmd
    - questionThree.qmd
    - question4.qmd
  sidebar:
    border: true
    background: light
    position: right
  navbar:
    background: light
    
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
  